name: PDPhoto
favicon: null
layout_spectrum: 0.421147
typography_spectrum: 0.125448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#FDFDFD'
    - '#BDBDBD'
    - '#888888'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
